### ISSUE TITLE
Missing icon for Long Swordsman

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#109]
Edit: ok, it's probably not a missing icon, but the crash happens anyway.
![2016-07-25 13-15-47](https://cloud.githubusercontent.com/assets/1813101/17098292/a700be24-5272-11e6-8860-ffddefcc90e2.png)

Bt:
```
Thread 1 "stratagus-dbg" received signal SIGSEGV, Segmentation fault.
0x0000000000a57477 in tolua_get_CIcon_G_ptr (tolua_S=0x1ae2bf0)
    at /home/kroartem/SVN/Wyrmgus/tolua.cpp:18216
18216	   tolua_pushusertype(tolua_S,(void*)self->G,"CPlayerColorGraphic");
(gdb) bt
#0  0x0000000000a57477 in tolua_get_CIcon_G_ptr (tolua_S=0x1ae2bf0)
    at /home/kroartem/SVN/Wyrmgus/tolua.cpp:18216
#1  0x00007ffff7bb5320 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#2  0x00007ffff7bb5734 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#3  0x00007ffff7bb1315 in lua_call ()
   from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#4  0x0000000000a95a1c in class_index_event ()
#5  0x00007ffff7bb5320 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#6  0x00007ffff7bb5734 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#7  0x00007ffff7bbe5d6 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#8  0x00007ffff7bbf94e in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#9  0x00007ffff7bb577d in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#10 0x00007ffff7bb4a5e in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#11 0x00007ffff7bb58eb in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#12 0x00007ffff7bb13a8 in lua_pcall ()
   from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#13 0x000000000087ed77 in LuaCall (narg=0, clear=0, exitOnError=true)
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/script.cpp:185
#14 0x000000000072e891 in TriggerExecuteAction (script=13)
    at /home/kroartem/SVN/Wyrmgus/src/game/trigger.cpp:508
#15 0x000000000072eb24 in TriggersEachCycle ()
    at /home/kroartem/SVN/Wyrmgus/src/game/trigger.cpp:570
#16 0x000000000085666f in GameLogicLoop ()
---Type <return> to continue, or q <return> to quit---
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/mainloop.cpp:486
#17 0x0000000000856d5a in SingleGameLoop ()
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/mainloop.cpp:670
#18 0x000000000085704a in GameMainLoop ()
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/mainloop.cpp:729
#19 0x000000000071797d in StartMap (
    filename="maps/random/random-map-dungeon.smp", clean=true)
    at /home/kroartem/SVN/Wyrmgus/src/game/game.cpp:193
#20 0x0000000000a2196e in tolua_stratagus_StartMap00 (tolua_S=0x1ae2bf0)
    at /home/kroartem/SVN/Wyrmgus/tolua.cpp:1075
#21 0x00007ffff7bb5320 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#22 0x00007ffff7bbfeea in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#23 0x00007ffff7bb577d in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#24 0x00007ffff7bb4a5e in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#25 0x00007ffff7bb58eb in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#26 0x00007ffff7bb13a8 in lua_pcall ()
   from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#27 0x0000000000852597 in LuaCallback::run (this=0x176b5b98, results=0)
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/luacallback.cpp:149
#28 0x00000000009502fc in LuaActionListener::action (this=0x176b5b90, 
    eventId="") at /home/kroartem/SVN/Wyrmgus/src/ui/widgets.cpp:494
#29 0x000000000073cb2e in gcn::Widget::generateAction (this=0x176b5950)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/widget.cpp:616
---Type <return> to continue, or q <return> to quit---
#30 0x000000000074018f in gcn::Button::mouseClick (this=0x176b5950, button=1)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/widgets/button.cpp:254
#31 0x000000000073c567 in gcn::Widget::_mouseInputMessage (this=0x176b5950, 
    mouseInput=...) at /home/kroartem/SVN/Wyrmgus/src/guichan/widget.cpp:502
#32 0x0000000000741e63 in gcn::Container::_mouseInputMessage (this=0x1765bae0, 
    mouseInput=...)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/widgets/container.cpp:394
#33 0x0000000000733ee0 in gcn::Gui::logic (this=0x170fa580)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/gui.cpp:155
#34 0x000000000095012b in handleInput (event=0x0)
    at /home/kroartem/SVN/Wyrmgus/src/ui/widgets.cpp:443
#35 0x0000000000a09066 in WaitEventsOneFrame ()
    at /home/kroartem/SVN/Wyrmgus/src/video/sdl.cpp:977
#36 0x000000000095c11b in MenuScreen::run (this=0x1765bae0, loop=true)
    at /home/kroartem/SVN/Wyrmgus/src/ui/widgets.cpp:3182
#37 0x0000000000a6e40f in tolua_stratagus_CMenuScreen_run00 (tolua_S=0x1ae2bf0)
    at /home/kroartem/SVN/Wyrmgus/tolua.cpp:27288
#38 0x00007ffff7bb5320 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#39 0x00007ffff7bbfeea in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#40 0x00007ffff7bb577d in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#41 0x00007ffff7bb4a5e in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#42 0x00007ffff7bb58eb in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#43 0x00007ffff7bb13a8 in lua_pcall ()
---Type <return> to continue, or q <return> to quit---
   from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#44 0x0000000000852597 in LuaCallback::run (this=0x175f9088, results=0)
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/luacallback.cpp:149
#45 0x00000000009502fc in LuaActionListener::action (this=0x175f9080, 
    eventId="") at /home/kroartem/SVN/Wyrmgus/src/ui/widgets.cpp:494
#46 0x000000000073cb2e in gcn::Widget::generateAction (this=0x1715fc00)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/widget.cpp:616
#47 0x000000000074018f in gcn::Button::mouseClick (this=0x1715fc00, button=1)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/widgets/button.cpp:254
#48 0x000000000073c567 in gcn::Widget::_mouseInputMessage (this=0x1715fc00, 
    mouseInput=...) at /home/kroartem/SVN/Wyrmgus/src/guichan/widget.cpp:502
#49 0x0000000000741e63 in gcn::Container::_mouseInputMessage (this=0x1759fb70, 
    mouseInput=...)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/widgets/container.cpp:394
#50 0x0000000000733ee0 in gcn::Gui::logic (this=0x170fa580)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/gui.cpp:155
#51 0x000000000095012b in handleInput (event=0x0)
    at /home/kroartem/SVN/Wyrmgus/src/ui/widgets.cpp:443
#52 0x0000000000a09066 in WaitEventsOneFrame ()
    at /home/kroartem/SVN/Wyrmgus/src/video/sdl.cpp:977
#53 0x000000000095c11b in MenuScreen::run (this=0x1759fb70, loop=true)
    at /home/kroartem/SVN/Wyrmgus/src/ui/widgets.cpp:3182
#54 0x0000000000a6e40f in tolua_stratagus_CMenuScreen_run00 (tolua_S=0x1ae2bf0)
---Type <return> to continue, or q <return> to quit---
    at /home/kroartem/SVN/Wyrmgus/tolua.cpp:27288
#55 0x00007ffff7bb5320 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#56 0x00007ffff7bbfe87 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#57 0x00007ffff7bb577d in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#58 0x00007ffff7bb4a5e in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#59 0x00007ffff7bb58eb in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#60 0x00007ffff7bb13a8 in lua_pcall ()
   from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#61 0x0000000000852597 in LuaCallback::run (this=0x171d2d68, results=0)
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/luacallback.cpp:149
#62 0x00000000009502fc in LuaActionListener::action (this=0x171d2d60, 
    eventId="") at /home/kroartem/SVN/Wyrmgus/src/ui/widgets.cpp:494
#63 0x000000000073cb2e in gcn::Widget::generateAction (this=0x17582880)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/widget.cpp:616
#64 0x000000000074018f in gcn::Button::mouseClick (this=0x17582880, button=1)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/widgets/button.cpp:254
#65 0x000000000073c567 in gcn::Widget::_mouseInputMessage (this=0x17582880, 
    mouseInput=...) at /home/kroartem/SVN/Wyrmgus/src/guichan/widget.cpp:502
#66 0x0000000000741e63 in gcn::Container::_mouseInputMessage (this=0x2112820, 
    mouseInput=...)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/widgets/container.cpp:394
#67 0x0000000000733ee0 in gcn::Gui::logic (this=0x170fa580)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/gui.cpp:155
---Type <return> to continue, or q <return> to quit---
#68 0x000000000095012b in handleInput (event=0x0)
    at /home/kroartem/SVN/Wyrmgus/src/ui/widgets.cpp:443
#69 0x0000000000a09066 in WaitEventsOneFrame ()
    at /home/kroartem/SVN/Wyrmgus/src/video/sdl.cpp:977
#70 0x000000000095c11b in MenuScreen::run (this=0x2112820, loop=true)
    at /home/kroartem/SVN/Wyrmgus/src/ui/widgets.cpp:3182
#71 0x0000000000a6e40f in tolua_stratagus_CMenuScreen_run00 (tolua_S=0x1ae2bf0)
    at /home/kroartem/SVN/Wyrmgus/tolua.cpp:27288
#72 0x00007ffff7bb5320 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#73 0x00007ffff7bbfe87 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#74 0x00007ffff7bb577d in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#75 0x00007ffff7bb4a5e in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#76 0x00007ffff7bb58eb in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#77 0x00007ffff7bb13a8 in lua_pcall ()
   from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#78 0x000000000087ed77 in LuaCall (narg=0, clear=1, exitOnError=true)
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/script.cpp:185
#79 0x000000000087f108 in LuaLoadFile (file="scripts/guichan.lua", strArg="")
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/script.cpp:246
#80 0x00000000008ee7fd in MenuLoop ()
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/stratagus.cpp:313
#81 0x00000000008ef2ca in stratagusMain (argc=1, argv=0x7fffffffdca8)
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/stratagus.cpp:822
---Type <return> to continue, or q <return> to quit---
#82 0x0000000000854bf4 in main (argc=1, argv=0x7fffffffdca8)
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/main.cpp:37
```

**Comment by Andrettin** [comment]
Thank you! Fixed now:
https://github.com/Andrettin/Wyrmsun/commit/8c15240636c431d8d4a9f34a922e74d856a0667a
