### ISSUE TITLE
Grand Strategy crash on Linux

### ISSUE THREAD

**Issue by Andrettin** [Andrettin/Wyrmsun#12]
A user reported the following crash when going to the grand strategy menu on Linux:

```
(gdb) bt
#0  0x00007ff0ddd0a0eb in __lll_lock_wait_private () from /usr/lib/libc.so.6
#1  0x00007ff0ddc908ac in malloc () from /usr/lib/libc.so.6
#2  0x00007ff0dfe3d25b in _dl_map_object_deps () from /lib64/ld-linux-x86-64.so.2
#3  0x00007ff0dfe43358 in dl_open_worker () from /lib64/ld-linux-x86-64.so.2
#4  0x00007ff0dfe3ef94 in _dl_catch_error () from /lib64/ld-linux-x86-64.so.2
#5  0x00007ff0dfe42e01 in _dl_open () from /lib64/ld-linux-x86-64.so.2
#6  0x00007ff0ddd3284d in do_dlopen () from /usr/lib/libc.so.6
#7  0x00007ff0dfe3ef94 in _dl_catch_error () from /lib64/ld-linux-x86-64.so.2
#8  0x00007ff0ddd328df in dlerror_run () from /usr/lib/libc.so.6
#9  0x00007ff0ddd32951 in __libc_dlopen_mode () from /usr/lib/libc.so.6
#10 0x00007ff0ddd0a965 in init () from /usr/lib/libc.so.6
#11 0x00007ff0df547dcf in __pthread_once_slow () from /usr/lib/libpthread.so.0
#12 0x00007ff0ddd0aa7c in backtrace () from /usr/lib/libc.so.6
#13 0x00007ff0ddc35b02 in backtrace_and_maps () from /usr/lib/libc.so.6
#14 0x00007ff0ddc87bad in __libc_message () from /usr/lib/libc.so.6
#15 0x00007ff0ddc8d0fe in malloc_printerr () from /usr/lib/libc.so.6
#16 0x00007ff0ddc8ff26 in _int_realloc () from /usr/lib/libc.so.6
#17 0x00007ff0ddc910f0 in realloc () from /usr/lib/libc.so.6
#18 0x00007ff0dd19917a in ?? () from /usr/lib/libnvidia-tls.so.352.21
#19 0x00000000007b352c in luaM_realloc_ ()
#20 0x00000000007b07b9 in luaD_reallocstack ()
#21 0x00000000007b130d in luaD_precall ()
#22 0x00000000007b1484 in luaD_call ()
#23 0x00000000007b938c in luaV_settable ()
#24 0x00000000007b9fad in luaV_execute ()
#25 0x00000000007b14cd in luaD_call ()
#26 0x00000000007b0757 in luaD_rawrunprotected ()
#27 0x00000000007b1662 in luaD_pcall ()
#28 0x00000000007aed1f in lua_pcall ()
#29 0x0000000000654e58 in LuaCall(int, int, bool) ()
#30 0x0000000000655168 in LuaLoadFile(std::string const&) ()
#31 0x000000000065541b in CclLoad(lua_State*) ()
#32 0x00000000007b10bc in luaD_precall ()
#33 0x00000000007ba6a8 in luaV_execute ()
#34 0x00000000007b14cd in luaD_call ()
#35 0x00000000007b0757 in luaD_rawrunprotected ()
#36 0x00000000007b1662 in luaD_pcall ()
#37 0x00000000007aed1f in lua_pcall ()
#38 0x000000000064ac3b in LuaCallback::run(int) ()
#39 0x00000000006cd1e5 in LuaActionListener::action(std::string const&) ()
#40 0x00000000005ca4e6 in gcn::Widget::generateAction() ()
#41 0x00000000005cd6e5 in gcn::Button::mouseClick(int, int, int, int) ()
#42 0x00000000005c9fac in gcn::Widget::_mouseInputMessage(gcn::MouseInput const&) ()
#43 0x00000000005cefd0 in gcn::Container::_mouseInputMessage(gcn::MouseInput const&) ()
#44 0x00000000005c2413 in gcn::Gui::logic() ()
#45 0x00000000006cd034 in handleInput(SDL_Event const*) ()
#46 0x0000000000747173 in WaitEventsOneFrame() ()
#47 0x00000000006d8670 in MenuScreen::run(bool) ()
#48 0x000000000078cc14 in tolua_stratagus_CMenuScreen_run00(lua_State*) ()
#49 0x00000000007b10bc in luaD_precall ()
#50 0x00000000007ba59b in luaV_execute ()
#51 0x00000000007b14cd in luaD_call ()
#52 0x00000000007b0757 in luaD_rawrunprotected ()
#53 0x00000000007b1662 in luaD_pcall ()
#54 0x00000000007aed1f in lua_pcall ()
#55 0x0000000000654e58 in LuaCall(int, int, bool) ()
#56 0x0000000000655168 in LuaLoadFile(std::string const&) ()
#57 0x0000000000674eed in MenuLoop() ()
#58 0x0000000000675738 in stratagusMain(int, char**) ()
#59 0x000000000064ad20 in main ()
```

Seems like an issue with the Lua code, rather than the engine itself.

**Comment by akien-mga** [comment]
Unrelated: You should try to use the ``` tags before pasting a backtrace, else the numbered references are interpreted as issue numbers, and you get cross-referencing like in all issues up to issue 11 currently: "Andrettin referenced this issue 5 days ago" (see the GitHub doc about Markdown formatting for details)

**Comment by akien-mga** [comment]
I could not reproduce the crash here with v1.3.1 on 64bit. I'll keep an eye out for such issues though.

**Comment by Andrettin** [comment]
Ops, I forgot to put the code tags, thanks for the heads up! Thanks for testing; I'll close this issue then since it could not be reproduced with version 1.3.1 (if someone reports it again I'll reopen it).

**Comment by akien-mga** [comment]
Actually I get this issue now, still with v1.3.1 (from Steam). The game freezes, with the music still playing to the end, and only this output in the terminal:
```
realloc(): invalid next size: 0x0000000006740ca0
```

**Comment by akien-mga** [comment]
I see you've investigated some minor lua issues in the grand strategy code lately, I'll check if it works better with the master branch.

**Comment by akien-mga** [comment]
I tried building the master branch on Mageia 5 and I get the same issue. The good news is that it's therefore not linked to the fact that we link Ubuntu 12.04's lua5.1 lib into the binary, as the binary I just compiled on Mageia uses the system-wide version of lua5.1 dynamically.

**Comment by akien-mga** [comment]
When I run the binary through gdb, I can't reproduce the issue anymore :-/

**Comment by Andrettin** [comment]
Based on some tests the user who reported this issue did, it seems that the error is due to the size of the argument for the SetWorldMapTerrain function in the world map definitions. As a fix to this issue, I changed the world maps to use the SetWorldMapTileTerrain for each tile now in https://github.com/Andrettin/Wyrmsun/commit/c531bd672fded65f93f24ec4a31281fcda48e156

The issue thus should be solved, but let me know if it persists :)

**Comment by akien-mga** [comment]
Ah indeed I can imagine that the argument was a bit heavy for lua. It's the kind of long stuff security researchers use to try to find vulnerabilities :-P

**Comment by akien-mga** [comment]
I confirm that it fixes the issue, well done :)

**Comment by Andrettin** [comment]
Nice :)
